Add MWL status to card zoom page
Null-Signal-Games/netrunnerdb pull request #160
Opened 2017-10-13 22:37 UTC by avandever

This is intended to address #14 . What it does:

- Display if the card is restricted
- Display if the card is banned (with flexible wording in case it's needed)

What it doesn't do:

- Display rotation status

Questions I have:

1. formatting - I think it's terrible right now, but I'm not sure what will look better. Should I just play around with it a bit more, or are there guidelines I should apply?
2. Ban wording - would it make more sense to just say "banned" instead of worrying about the specific deck limit? That would be an easy change
3. i18n - Is there some framework for this I should be tapping into?

2017-10-16 10:54 UTC, gereons commented
I'd simply use the vocabulary from the MWL document: "restricted" and "removed". Also, it's probably useful to include the MWL version number.

2017-10-18 07:32 UTC, avandever commented
New screenshots:
<img width="494" alt="screenshot 2017-10-18 00 30 42" src="https://user-images.githubusercontent.com/1231665/31705827-a7cdae6c-b39b-11e7-9108-31ffd90f98e6.png">
<img width="497" alt="screenshot 2017-10-18 00 23 40" src="https://user-images.githubusercontent.com/1231665/31705755-7626f9e0-b39b-11e7-9bad-0e4a0b78a45c.png">
<img width="494" alt="screenshot 2017-10-18 00 23 45" src="https://user-images.githubusercontent.com/1231665/31705756-7655205e-b39b-11e7-83ab-7edcb7f62533.png">

I still feel like there's got to be a better formatting option, maybe more similar to Rulings.

2017-10-18 07:47 UTC, avandever commented
Yeah, I feel much better about this. Please let me know what you think.
<img width="505" alt="screenshot 2017-10-18 00 44 49" src="https://user-images.githubusercontent.com/1231665/31706419-c5784916-b39d-11e7-9b62-7827873042dc.png">
<img width="516" alt="screenshot 2017-10-18 00 44 55" src="https://user-images.githubusercontent.com/1231665/31706420-c5a53804-b39d-11e7-9c0d-0053afbadb21.png">
<img width="516" alt="screenshot 2017-10-18 00 45 02" src="https://user-images.githubusercontent.com/1231665/31706421-c5c40a68-b39d-11e7-83e0-2ea47346c2da.png">

2017-10-18 08:30 UTC, Alsciende commented
I like it a lot, thank you.

2017-10-20 06:08 UTC, alsciende requested changes
Sorry it took me several day to look at your PR. I like it, I'm just questioning why you didn't use the property Mwl.active.

2017-10-20 06:08 UTC, Alsciende commented on src/AppBundle/Service/CardsData.php
> +            if ($card_mwl !== null) {
On pourra aller un poil plus vite en faisant un `if (isset($mwl_cards[$card_code]))` ici et en créant la variable `$card_mwl` à l'instruction suivante.

2017-10-20 06:08 UTC, Alsciende commented on src/AppBundle/Service/CardsData.php
> +        $card_code = (string) $card->getCode();
`getCode` renvoie déjà un `string`, pas besoin de caster

2017-10-20 06:08 UTC, Alsciende commented on src/AppBundle/Service/CardsData.php
> +                    $found_current = true;
Pourquoi ne pas utiliser la propriété `Mwl.getActive()` ?

2017-10-24 15:08 UTC, avandever commented on src/AppBundle/Service/CardsData.php
> +                    $found_current = true;
Doh! I hadn't run nrdb:legality:active-mwl, so it seemed it was either broken or intended for something else. :(

2017-10-25 07:01 UTC, alsciende approved these changes

2017-10-25 07:01 UTC, merged

2017-10-26 07:04 UTC, Alsciende commented
deployed!

2017-10-26 14:41 UTC, gereons commented
Not sure if it's a server-side caching issue, but I only see info up to MWL 1.2.