add a z:current filter option
Null-Signal-Games/netrunnerdb pull request #414
Opened 2020-02-04 21:11 UTC by opaldes

#309

2020-02-05 16:17 UTC, NoahTheDuke commented
Thanks for this! I'll test it out and see!

2020-02-15 16:06 UTC, plural requested changes
This is excellent!  I patched it in and it works well.

Please also update the syntax page at app/Resources/views/Default/syntax.html.twig and the tooltip for syntax at app/Resources/views/Search/searchtooltip.html.twig

(i should pull those together so we don't have them duplicated...)

Another option we could consider here is expanding this just a little bit:

z:rotation#|current|latest

the rotations have names and codes in the DB right now, but AFAIK, they aren't shown anywhere.

mysql> SELECT * FROM rotation;
+----+---------------+-----------------+---------------------+---------------------+------------+
| id | code          | name            | date_creation       | date_update         | date_start |
+----+---------------+-----------------+---------------------+---------------------+------------+
|  1 | rotation-2017 | First Rotation  | 2019-12-26 22:29:02 | 2019-12-26 22:29:02 | 2017-10-01 |
|  2 | rotation-2018 | Second Rotation | 2019-12-26 22:29:02 | 2019-12-26 22:29:02 | 2018-12-21 |
|  3 | rotation-2019 | Third Rotation  | 2019-12-26 22:29:02 | 2019-12-26 22:29:02 | 2019-12-27 |
+----+---------------+-----------------+---------------------+---------------------+------------+

2020-02-15 16:06 UTC, plural commented on src/AppBundle/Service/RotationService.php
> +        $rotations = $this->entityManager->getRepository(Rotation::class)->findBy([], ['dateStart' => 'DESC']);
you could also consider

$rotation = $this->entityManager->getRepository(Rotation::class)->findOneBy([], ['dateStart' => 'DESC']);
if (!$rotation) {
  throw ...
}
return $rotation;

2020-02-18 01:32 UTC, opaldes commented on src/AppBundle/Service/RotationService.php
> +        $rotations = $this->entityManager->getRepository(Rotation::class)->findBy([], ['dateStart' => 'DESC']);
will do seems better because we expect only 1 to return

2020-02-19 14:58 UTC, jeremy-seipelt commented on src/AppBundle/Service/RotationService.php
> +        $rotations = $this->entityManager->getRepository(Rotation::class)->findBy([], ['dateStart' => 'DESC']);
@plural do we want z:"First Rotation" or z:rotation-2017 ? I would change my function appropriately

2020-02-23 16:03 UTC, plural commented on src/AppBundle/Service/RotationService.php
> +        $rotations = $this->entityManager->getRepository(Rotation::class)->findBy([], ['dateStart' => 'DESC']);
no quoting is better, i think, so i would go with rotation-2017.  We can always publish the names of the valid rotation strings on the syntax page to help people out, too.

2020-04-06 16:01 UTC, plural commented
hey @opaldes, do you want to push ahead with this or have one of us run with it?  Thanks for kicking this off.

2020-04-08 01:10 UTC, plural commented
i ran with this in #427 and merged it in.  Thanks again to @opaldes and @jeremy-seipelt for kicking this off!

2020-04-08 01:10 UTC, closed without merging