add a prohibited emoji to the unicorn function
Null-Signal-Games/netrunnerdb pull request #415
Opened 2020-02-04 23:03 UTC by opaldes

2020-02-05 16:18 UTC, NoahTheDuke commented
Thanks for this! I'll test it out and hopefully we can get it live soon.

2020-02-15 16:24 UTC, plural requested changes
nice, thanks!  This looks great.  I don't know of any other places that need this off the top of my head, but we'll find them when we release it if we missed any.  :D

2020-02-15 16:24 UTC, plural commented on web/js/nrdb.js
> + *  takes a card and adds an unicorn based on the current card
how about "Returns a banned or restricted icon for the supplied card and selected MWL." ?

2020-02-15 16:24 UTC, plural commented on web/js/nrdb.js
> +    var prohibited_emoji = ' <span title="Restricted card" style="display:inline-block;width:1.5em;">🚫</span> ';
not strictly a necessary change, but since you only use each of these once, you could just move them into the conditional block and remove the other variables.

if (mwlCard.is_restricted) {
  return "blah blah"
} else if (mwlCard.deck_limit == 0) {
  return "blah blah"
}
return "";

2020-02-18 01:28 UTC, opaldes commented on web/js/nrdb.js
> + *  takes a card and adds an unicorn based on the current card
Seems reasonable

2020-04-06 16:00 UTC, plural commented
hey @opaldes this is great.  Did you want to pick this back up or have one of us run with it?  This will be a really nice improvement for the UI!

2020-04-08 01:18 UTC, plural commented
big thanks to @opaldes for getting this kicked off.  I ran with this in #426 because we didn't hear back for a bit.

2020-04-08 01:18 UTC, closed without merging