Add Borealis set icon.
Null-Signal-Games/netrunnerdb pull request #607
Opened 2022-03-07 02:07 UTC by plural

<img width="973" alt="Screen Shot 2022-03-06 at 8 06 37 PM" src="https://user-images.githubusercontent.com/396562/156955693-c6fcb003-11e8-4428-85f1-3d327dc56732.png">
<img width="979" alt="Screen Shot 2022-03-06 at 8 06 44 PM" src="https://user-images.githubusercontent.com/396562/156955703-64d0ef3c-3542-49af-a338-535ee5218798.png">
<img width="315" alt="Screen Shot 2022-03-06 at 8 06 54 PM" src="https://user-images.githubusercontent.com/396562/156955708-322f6f08-3283-44e9-ae83-047c9a35fb0b.png">

2022-03-07 14:26 UTC, NoahTheDuke requested changes
Should the composer.lock file be updated here? I don't see any reason for the change.

2022-03-07 14:26 UTC, NoahTheDuke commented on web/netrunnerfont.css
> +  content: "\e925";
This is already taken by kitara, so that's why the svg has such a big diff.

2022-03-07 14:52 UTC, plural commented on web/netrunnerfont.css
> +  content: "\e925";
nope, the composer.lock change was just an accident.  Reverted.

Re: the SVG.  grrrrrrrrr.  the process for doing this is janky and apparently i did it wrong.  I'll look more closely tonight.

2022-03-07 14:54 UTC, NoahTheDuke commented on web/netrunnerfont.css
> +  content: "\e925";
yeah it's really really really annoying lol. i think it's append-only? can't insert in the middle of the list.

2022-03-08 03:11 UTC, plural commented on web/netrunnerfont.css
> +  content: "\e925";
ah, i figured out what happened.  I had imported the icon twice after fiddling with the size.  I left one accidentally in the middle of the grid.  Ooops!  Turns out if you do that and remove it, icomoon doesn't reset the number properly for you.  Live and learn.

2022-03-08 13:07 UTC, NoahTheDuke approved these changes

2022-03-08 13:42 UTC, merged