New api ban list page
Null-Signal-Games/netrunnerdb pull request #689
Opened 2022-09-12 17:14 UTC by distributive

- Updated the ban list page to dynamically load from the new API (requires the api to be running locally)
- Improved the layout of the ban list page (see below)
- Started a js file for general purpose v2api functions
- The ban list search query (b:...) now correctly interprets the inverse operator (b!...)

Some notes:
- The ban list search query seems to fail with older restriction types (universal faction cost, global penalty)
- Due to limitations on the api I haven't been able to work out, this version loads the entire card pool and then manually filters it for cards on each list (probably should not be made live until fixed)

2022-09-19 13:53 UTC, plural commented
sync in main and use the new config variable for the API.  We can get the API deployed shortly with your change for latest printing ID as well, but i am also going to take a crack at a couple of materialized views for cards and printings that may simplify things a bit as well.

2022-09-21 17:21 UTC, distributive commented
This still loads all card data every time the page is loaded, but that can be fixed when the api allows for it.

2022-09-22 05:06 UTC, plural requested changes
sorry for the pile of comments.

2022-09-22 05:06 UTC, plural commented on web/css/style.css
> +
do you need a whitespace-only change to this file?

2022-09-22 05:06 UTC, plural commented on web/js/api.js
> +async function fetchCards() {
something to consider until we have some proper ember stuff in place is what goes in an external JS file vs. a template included inline.

The way i did the formats page kept things inline at the end of the body without extra loads (except for the API calls obviously).

Since we don't have great (ha! any) cache busting for our JS, it might be good to not add too many new JS files to NRDB classic.

I would personally move this to a template we could include from the twig files side, I'm curious what @locks has to say here, though.

2022-09-22 05:06 UTC, plural commented on web/js/api.js
> +async function fetchCards() {
also, YAY for starting to sort out some common client side libs we need.

2022-09-22 05:06 UTC, plural commented on web/js/api.js
> +  return cards.filter(c => subtypes.some(s => !(c.attributes.display_subtypes && c.attributes.display_subtypes.toLowerCase().split(' - ').includes(s))));
formatting nit, are there some more convenient line breaks / a lurking helper function here?

since we are only using this for currents right now, should this just be a "remove currents?" function?  I'd rather expose the subtype ids for operations rather than rely on the display subtypes.

2022-09-22 05:06 UTC, plural commented on web/js/api.js
> +  return cards.filter(c => subtypes.some(s => !(c.attributes.display_subtypes && c.attributes.display_subtypes.toLowerCase().split(' - ').includes(s))));
Also, you can include subtypes in the cards API call if you use https://api-preview.netrunnerdb.com/api/v3/public/cards/?include=card_subtypes

For Abagnale this adds:
```
"data": [
{
"type": "card_subtypes",
"id": "decoder"
},
{
"type": "card_subtypes",
"id": "icebreaker"
}
]
```

to relationships.card_subtypes

2022-09-22 05:06 UTC, plural commented on web/js/api.js
> +function getRestrictionById(restrictions, id) {
consider what i did for the formats page?  https://github.com/NetrunnerDB/netrunnerdb/blob/main/app/Resources/views/Formats/formats.html.twig#L25

this method is not needed if the data is transformed into a map.

2022-09-22 05:06 UTC, plural commented on web/js/api.js
> +function cardToLink(card) {
cardToLatestPrintingLink ?

2022-09-22 05:06 UTC, plural commented on src/AppBundle/Service/CardsData.php
> +                        $cond = $operator == ":" ? "in" : "not in";
this could be its own PR

2022-09-22 05:06 UTC, plural commented on app/Resources/views/Banlists/banlists.html.twig
> +<script>
a couple of general things in here. 

would you please make the variables const where you can?
would you please make a pass through for formatting and indentation? There are some blocks that are pretty bunched up.

Also, could we do jquery dom manipulation here instead of string literals?  it would be good to be consistent for the pages we are changing.

2022-09-22 07:57 UTC, distributive commented on web/css/style.css
> +
Oops! This is left over from a temporary addition to the file.

2022-09-22 07:59 UTC, distributive commented on src/AppBundle/Service/CardsData.php
> +                        $cond = $operator == ":" ? "in" : "not in";
I can move it if you want, but technically this pr relies on it as otherwise there's no valid search to link to for cards affected by a banlist (although it still doesn't work for points or universal costs, etc)

2022-09-22 08:10 UTC, distributive commented on web/js/api.js
> +  return cards.filter(c => subtypes.some(s => !(c.attributes.display_subtypes && c.attributes.display_subtypes.toLowerCase().split(' - ').includes(s))));
Does the include let me get a explicit list of subtypes without making additional queries? I can't find one.

I think having the subtypes be exposed as a list that users have to join with " - " would make more sense to me.

2022-09-22 14:39 UTC, plural commented on src/AppBundle/Service/CardsData.php
> +                        $cond = $operator == ":" ? "in" : "not in";
ah, i didn't realize it was needed here.  Carry on.  :D

2022-09-22 14:40 UTC, plural commented on web/js/api.js
> +  return cards.filter(c => subtypes.some(s => !(c.attributes.display_subtypes && c.attributes.display_subtypes.toLowerCase().split(' - ').includes(s))));
yeah, take a look at the API link - include will include the ids for the related attributes and for things like card subtypes the id is the only thing you need.  this all happens in one http request to the API.

2022-09-22 14:55 UTC, distributive commented on web/js/api.js
> +  return cards.filter(c => subtypes.some(s => !(c.attributes.display_subtypes && c.attributes.display_subtypes.toLowerCase().split(' - ').includes(s))));
Ohhh I see! That's really useful, thanks!

2022-09-25 05:00 UTC, plural requested changes

2022-09-25 05:00 UTC, plural commented on app/Resources/views/Banlists/banlists.html.twig
> +  const formats = await Promise.all(desiredFormats.map(f => fetch(`{{ v3_api_url }}/api/v3/public/formats/${f}`).then(data => data.json()).then(json => json.data)));
couple of options for you here.

you don't need to grab the formats from the API.  

You could just call /api/v3/public/formats/${format}/restrictions OR just get all the restricitons in 1 API call and filter them here.

Additionally, you can sort in the API call: /api/v3/public/formats/standard/restrictions?sort=-date_start

2022-09-25 05:00 UTC, plural commented on app/Resources/views/Banlists/banlists.html.twig
> +      let cards = await fetchCards(`?include=card_subtypes&filter[search]=in_restriction:true restriction_id:${r.id}`).then(cards => splitBySide(cards));
Fetching cards I think you can do in a single call.

/me checks some stuff

We'll need one other change to allow this to be done in a single call. I'll send you that PR in a minute.

The call you can make is http://localhost:3000/api/v3/public/cards?filter%5Bsearch%5D=in_restriction%3Atrue&page[limit]=250&page[offset]=0

we have a max page size of 1000 and a default of 100, but you can override it.

Since you have the restrictions and they have all the card ids, you could client-side slice these up from the single cards call.  I think this brings the number of requests down from 28 -> 4.

2022-09-25 05:00 UTC, plural commented on app/Resources/views/layout.html.twig
> +    <script src="{{ asset('/js/api.js') }}"></script>
you don't need this any longer.

2022-09-25 05:01 UTC, plural commented
the layout looks great!  I would keep all but the most recent (or the active one) collapsed by default.

2022-09-25 08:44 UTC, distributive commented on app/Resources/views/layout.html.twig
> +    <script src="{{ asset('/js/api.js') }}"></script>
Oops, yeah!

2022-09-25 09:20 UTC, distributive commented on app/Resources/views/Banlists/banlists.html.twig
> +  const formats = await Promise.all(desiredFormats.map(f => fetch(`{{ v3_api_url }}/api/v3/public/formats/${f}`).then(data => data.json()).then(json => json.data)));
Technically I need the formats for showing their names and setting some IDs, but given I've hardcoded in the three formats we want I'm happy to just hardcode those too

2022-09-25 09:21 UTC, distributive commented on app/Resources/views/Banlists/banlists.html.twig
> +  const formats = await Promise.all(desiredFormats.map(f => fetch(`{{ v3_api_url }}/api/v3/public/formats/${f}`).then(data => data.json()).then(json => json.data)));
Is it better to make 1 call over 3? I'm happy to do either, I'm just wondering if there's a preference

2022-09-25 09:25 UTC, distributive commented on app/Resources/views/Banlists/banlists.html.twig
> +      let cards = await fetchCards(`?include=card_subtypes&filter[search]=in_restriction:true restriction_id:${r.id}`).then(cards => splitBySide(cards));
No restriction has actually reached 100 cards yet (although it might one day if they ban another subtype)

I'll get it to manually slice these up though

2022-09-25 09:27 UTC, distributive commented
> the layout looks great! I would keep all but the most recent (or the active one) collapsed by default.

Sure thing!

If we're happy with this layout, in a later PR I'll separate the code into another library and start using it for other pages

2022-09-25 09:29 UTC, distributive commented on app/Resources/views/Banlists/banlists.html.twig
> +  const formats = await Promise.all(desiredFormats.map(f => fetch(`{{ v3_api_url }}/api/v3/public/formats/${f}`).then(data => data.json()).then(json => json.data)));
Wait, I need the formats themselves to determine the active restriction 😐

2022-09-25 09:44 UTC, distributive commented on app/Resources/views/Banlists/banlists.html.twig
> +  const formats = await Promise.all(desiredFormats.map(f => fetch(`{{ v3_api_url }}/api/v3/public/formats/${f}`).then(data => data.json()).then(json => json.data)));
If we're enforcing that restrictions only belong to one format then we can add an `active` flag to them themselves to get around this

2022-09-25 15:41 UTC, plural commented on app/Resources/views/Banlists/banlists.html.twig
> +  const formats = await Promise.all(desiredFormats.map(f => fetch(`{{ v3_api_url }}/api/v3/public/formats/${f}`).then(data => data.json()).then(json => json.data)));
AH, right.  Names come from format calls.   A mirrored active flag for restrictions is a good idea - we can handle that separately, though.

I think your minimal set of requests is:
- get all formats
- get all restrictions
- get all cards on any restrictions

and all of those can happen in parallel.

we definitely should aim for the fewest # of requests we can get away with - it will be more responsive to the user and cause less load on the server.

2022-09-27 04:52 UTC, plural commented on app/Resources/views/Banlists/banlists.html.twig
> +  <noscript>
the site is gonna be pretty sad without JS.  hehe

2022-09-27 05:00 UTC, plural approved these changes
This looks fantastic!

2022-09-27 08:14 UTC, merged