Update trace text format
Null-Signal-Games/netrunnerdb pull request #705
Opened 2022-10-25 03:51 UTC by mankinchi

Handling the styling issue mentioned in https://github.com/NetrunnerDB/netrunnerdb/issues/623. This would also requires some cards data change to work properly

2022-10-25 13:19 UTC, plural requested changes
Please update to keep the match against the trace in the json as well.

Please also run locally and make sure things look ok.

2022-10-27 13:08 UTC, plural requested changes
just one small thing.

2022-10-27 13:08 UTC, plural commented on src/AppBundle/Service/CardsData.php
> +            $cardinfo['text'] = preg_replace('/<trace>.*([X\d]+)<\/trace>/', '<span>Trace [\1]</span>.', $cardinfo['text']);
please make the `.*` not greedy with `.*?` or use the original capture group here.

2022-11-25 08:01 UTC, mankinchi commented
so sorry for the disappearance. Personal issue is annoying but resolved. I will look back into this and update it asap 😄

2022-12-26 16:50 UTC, plural commented
I ended up taking care of this in #725 .  Thank you for kicking this off!

2022-12-26 16:50 UTC, closed without merging