Sanitize instead of escape
Null-Signal-Games/netrunnerdb pull request #868
Opened 2024-11-22 01:17 UTC by xdg

PR #846 escaped special HTML characters in raw user-provided text, such as deck notes, with the unintentional side effect that these entities were encoded on save, and then re-encoded on the next save, etc. leaving deck notes, etc. effectively un-editable from a practical perspective.

This PR reverts #846 and replaces it with HTML sanitization using DOM Purify when raw user-provided text is rendered via Javascript.

Fixes #864.

2024-11-23 14:05 UTC, plural commented
Thanks! One other thing is that the preview does not appear to be working with this PR.  While typing deck notes, the preview box stays static:
<img width="595" alt="Screenshot 2024-11-23 at 9 05 17 AM" src="https://github.com/user-attachments/assets/6f6dd34d-f078-4d4a-818f-dfe40f3c9f35">

2024-11-23 14:06 UTC, plural requested changes

2024-11-23 14:06 UTC, plural commented on src/AppBundle/Controller/BuilderController.php
> +        $description = trim($request->get('description'));
We can't trust the client to always send us good data.   The JS side stuff is helpful, but we'll need server side sanitization as a backstop.

2024-11-23 14:06 UTC, plural commented on src/AppBundle/Controller/BuilderController.php
> +        $description = trim($request->get('description'));
We have HTMLPurifier available on the backend via the TextProcessor service that we can use for this.

```diff
--- a/src/AppBundle/Controller/BuilderController.php
+++ b/src/AppBundle/Controller/BuilderController.php
@@ -12,6 +12,7 @@ use AppBundle\Entity\User;
 use AppBundle\Service\CardsData;
 use AppBundle\Service\DeckManager;
 use AppBundle\Service\Judge;
+use AppBundle\Service\TextProcessor;
 use Doctrine\ORM\EntityManagerInterface;
 use Psr\Log\LoggerInterface;
 use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
@@ -630,11 +631,12 @@ class BuilderController extends Controller
      * @param Request                $request
      * @param EntityManagerInterface $entityManager
      * @param DeckManager            $deckManager
+     * @param TextProcessor          $textProcessor
      * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
      *
      * @IsGranted("IS_AUTHENTICATED_REMEMBERED")
      */
-    public function saveAction(Request $request, EntityManagerInterface $entityManager, DeckManager $deckManager)
+    public function saveAction(Request $request, EntityManagerInterface $entityManager, DeckManager $deckManager, TextProcessor $textProcessor)
     {
         /** @var User $user */
         $user = $this->getUser();
@@ -674,7 +676,7 @@ class BuilderController extends Controller
         }
         $name = filter_var($request->get('name'), FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES);
         $decklist_id = intval(filter_var($request->get('decklist_id'), FILTER_SANITIZE_NUMBER_INT));
-        $description = trim($request->get('description'));
+        $description = $textProcessor->purify(trim($request->get('description')));
         $tags = explode(',', filter_var($request->get('tags'), FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES));
         $mwl_code = $request->get('format_casual') ? null : $request->get('mwl_code');

```

should do it, but i think we need something similar on decklist publishing as well.  You could do that here or we can do a followup.

2024-11-23 14:40 UTC, xdg commented
The preview box not updating until keypress is like that on the deployed nrdb already.

![](https://www.dropbox.com/scl/fi/qvb7fe7e3ms8apx8zckq7/2024-11-23_09-38.png?rlkey=rjee8ugk9fugu5xuv854yjb2j&dl=0&raw=1)

2024-11-23 14:51 UTC, xdg commented on src/AppBundle/Controller/BuilderController.php
> +        $description = trim($request->get('description'));
OK, I'll make that change.  Published decks get sanitized via `markdown` here: https://github.com/NetrunnerDB/netrunnerdb/blob/main/src/AppBundle/Controller/SocialController.php#L129

2024-11-23 15:06 UTC, plural commented
Locally with your or parched in deck notes preview is not updating even
when changing the contents.

I’m not at my computer at the moment to look more closely though.



On Sat, Nov 23, 2024 at 9:40 AM David Golden ***@***.***>
wrote:

> The preview box not updating until keypress is like that on the deployed
> nrdb already.
>
>
> <https://camo.githubusercontent.com/425a3c57fdd83e4433e3a5d34c9444bf020e128439927cad4aeff0c937322e98/68747470733a2f2f7777772e64726f70626f782e636f6d2f73636c2f66692f7176623766653765336d7338617078387a636b71372f323032342d31312d32335f30392d33382e706e673f726c6b65793d726a65653875676b396675677535787576383534796a62326a26646c3d30267261773d31>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NetrunnerDB/netrunnerdb/pull/868#issuecomment-2495500647>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADA2EXU5ZKXCAOWKKPL3O32CCHXNAVCNFSM6AAAAABSIIV7MGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJVGUYDANRUG4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-23 22:01 UTC, plural commented on src/AppBundle/Controller/BuilderController.php
> +        $description = trim($request->get('description'));
Ah.  i had locally cached JS.  Clearing the cache makes the preview work.

2024-11-29 19:57 UTC, plural approved these changes

2024-11-29 19:57 UTC, merged

2024-12-17 02:34 UTC, Phamduy1247 commented
app/Resources/views/Banlists/banlists.html.twig

2024-12-17 03:38 UTC, plural commented
> app/Resources/views/Banlists/banlists.html.twig

?